image: gitpod/workspace-java-17

tasks:
  - name: Build and Test
    init: mvn install -DskipTests=true
    command: mvn test

# Environment variables for LambdaTest credentials
env:
  LT_USERNAME: ${LT_USERNAME}
  LT_ACCESS_KEY: ${LT_ACCESS_KEY}

ports:
  - port: 4444
    onOpen: ignore
  - port: 7900
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven
