image:
  file: .gitpod.Dockerfile

tasks:
  - before: |sdk install java 17.0.4.1-tem
  - init: |
      mvn install -DskipTests=true
    command: |
      mvn test

ports:
  - port: 4444
    onOpen: ignore
  - port: 7900
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven
